### PR TITLE
[MINOR] Use rssConf instead of sparkConf to avoid unnecessary parsing to generate rssConf.

### PR DESCRIPTION
**Pull request by wForget**
# [BUG]/[FEATURE] title

### What changes were proposed in this pull request?

Use rssConf instead of sparkConf to avoid unnecessary parsing to generate rssConf.

### How was this patch tested?

/cc @related-reviewer

/assign @main-reviewer

### CODE REVIEW

**Comment by pan3793** [comment]
Do we have similar logic in spark-2 module?

**Comment by wForget** [comment]
> Do we have similar logic in spark-2 module?

Yes, I will fix it.

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Review by FMX — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
