### PR TITLE
[Feature] Shade netty native libraries

### LINKED ISSUE #907: [FEATURE] Shade netty native libraries.
### Describe the solution you'd like
Shade netty native library and remove unused native libraries. Celeborn will keep Epoll native library only. So Linux server will be required for deployment.

### Describe alternatives you've considered

/cc @who-need-to-know

/assign @who-can-help-you

### PR DESCRIPTION
**Pull request by FMX**
# [Feature]Shade netty native libraries.

### Related issues.
closes #907 

### How was this patch tested?

/cc @related-reviewer

/assign @main-reviewer

### CODE REVIEW

**Comment by FMX** [comment]
Shade result.
截屏2022-11-02 15 21 01
As you can see,  the x86 native libraries are shaded.I assume that we won't run Celeborn on arm devices.

**Comment by waitinfuture** [comment]
cc @pan3793

**Comment by waitinfuture** [comment]
How can we be sure Celeborn will look for the shaded so file first place?

**Comment by FMX** [comment]
> Is it guaranteed that Celeborn will look for the shaded so file first place?

Interesting question, I am wondering as well. Let me check.

**Comment by FMX** [comment]
Netty native library loader did try to load shade library.

> 
>     public static void load(String originalName, ClassLoader loader) {
>         // Adjust expected name to support shading of native libraries.
>         String packagePrefix = calculatePackagePrefix().replace('.', '_');
>         String name = packagePrefix + originalName;
>         List<Throwable> suppressed = new ArrayList<Throwable>();
>         try {

**Comment by pan3793** [comment]
> I assume that we won't run Celeborn on arm devices.

In fact kqueue is used on macOS and freeBSD, and w/o them, Celeborn could fallback to NIO mode, epoll is dedicated for Linux, and arm64 become popularly in recently days.

I suggest to ship epoll for all arch.

**Comment by FMX** [comment]
> 

ok，I'll shade all arch.

**Review by pan3793 — APPROVED** [review]

**Comment by FMX** [comment]
The regression is completed with no error.
https://github.com/alibaba/celeborn/actions/runs/3376487815/jobs/5604268464

**Pull request merged**
