### PR TITLE
[ISSUE-902][BUG] LifecycleManager should not reallocate slots in failed worker during retry

### LINKED ISSUE #902: [BUG] Blacklist should not clean worker that is shutting down to avoid retry on shutting down worker
### How to reproduce the bug?
Steps to reproduce the bug.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### Related issues.
close #902

### How was this patch tested?

/cc @related-reviewer

/assign @main-reviewer

### CODE REVIEW

**Comment by waitinfuture** [comment]
I think this pr is unnecessary. This pr reserves additional three status to avoid delete from LifecycleManager's blacklist
```
          case StatusCode.WORKER_SHUTDOWN => true
          case StatusCode.NO_AVAILABLE_WORKING_DIR => true
          case StatusCode.RESERVE_SLOTS_FAILED => true
```
1. For WORKER_SHUTDOWN, master will keep the worker in blacklist, so it's unnecessary to handle this.
2. For NO_AVAILABLE_WORKING_DIR and RESERVE_SLOTS_FAILED, these two errors should not be considered forever critical errors, for example HIGH_DISK_USAGE can transfer to HEALTHY after cleanup.

**Comment by AngersZhuuuu** [comment]
> I think this pr is unnecessary. This pr reserves additional three status to avoid delete from LifecycleManager's blacklist
> 
> ```
>           case StatusCode.WORKER_SHUTDOWN => true
>           case StatusCode.NO_AVAILABLE_WORKING_DIR => true
>           case StatusCode.RESERVE_SLOTS_FAILED => true
> ```
> 
> 1. For WORKER_SHUTDOWN, master will keep the worker in blacklist, so it's unnecessary to handle this.
> 2. For NO_AVAILABLE_WORKING_DIR and RESERVE_SLOTS_FAILED, these two errors should not be considered forever critical errors, for example HIGH_DISK_USAGE can transfer to HEALTHY after cleanup.

The problem is that during reserve slots retry if the blacklist request clears all workers with problems. retry will allocate again in that worker.

Then register shuffle failed. So at least, we should reserve failed workers  during reserve slots.

**Comment by AngersZhuuuu** [comment]
@waitinfuture  How about current?

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
